### ISSUE TITLE
Collecting multicast traffic

### ISSUE THREAD

**Issue by dsuded** [netoptimizer/IPTV-Analyzer#25]
Hello,

How do I collect multicast traffic? I used rule iptales -t mangle -I PREROUTING -p udp -m mpeg2ts.
PC ethernet port is plugged in wall jack where the st was plugged in. iptv-collector daemon starts normally without error msgs.
Output from /var/log/mysql/mysql.log looks like this:

`36 Connect debian-sys-maint@localhost on 
           36 Query select @@version_comment limit 1
           36 Query select count(*) into @discard from`mysql`.`user`
           36 Quit  
160723 13:41:24    37 Connect   tvprobe@localhost on tvprobe
           37 Query set autocommit=0
           37 Query SELECT * FROM probes WHERE ip = '10.1.14.129'       AND input = 'rule_in_eth0'   AND shortloc = 'alb' AND switch = 'albcr3' LIMIT 1
           37 Query INSERT INTO probes  (input, ip, name, shortloc, switch,  description, location, address, distance,  input_ip, input_dev,   procfile, switchport, switchtype, hidden ) VALUES ('rule_in_eth0', '10.1.14.129', 'tvprobe-dev2', 'alb', 'albcr3', 'Main signal', 'Serverrum A', 'Herstedvang 42, 2620 Albertslund', '2', '10.100.13.115', 'eth0', '/proc/net/xt_mpeg2ts/rule_1', 'e1/4', 'HP9300', 'no')
           37 Query commit
`

/proc/net/xt_mpeg2ts/rule_1 is this:

`info:version module:xt_mpeg2ts version:0.9.4
 info:time created:1469272777.927941168 now:1469274206.454475226 delta:1428.526534058
 info:dynamic rule_id:1 streams:0 streams_check:0 max_list_search:0 rnd:0
 info:config htable_size:100 max-streams:0 list_search_warn_level:20`

IP address in collector.conf is from pc.
Any help appreciated.
Thanks.

**Comment by Raifeg** [comment]
Try enabling promisc mode on the interface.

**Comment by dsuded** [comment]
Thanks, it's solved. Reloading iptables did the trick.
